import { Product } from './types';

export const products: Product[] = [
    {
        id: '1',
        name: 'Flying Plane',
        img: '/images/dev/flying-plane.jpg',
        price: 99.99,
        category: 'Electronics',
        description: '',
    },
    {
        id: '2',
        name: 'Racing Car',
        img: '/images/dev/racing-car.jpg',
        price: 149.99,
        category: 'Electronics',
        description: '',
    },
    {
        id: '3',
        name: 'Dragon Doll',
        img: '/images/dev/dragon-doll.jpg',
        price: 129.99,
        category: 'Dolls',
        description: '',
    },
    {
        id: '4',
        name: 'Jade Necklace',
        img: '/images/dev/jade-necklace.jpg',
        price: 249.99,
        category: 'Jewelry',
        description: '',
    },
    {
        id: '5',
        name: 'Favor Ring',
        img: '/images/dev/favor-ring.jpg',
        price: 249.99,
        category: 'Jewelry',
        description: '',
    },
    {
        id: '6',
        name: 'Dancing Robot',
        img: '/images/dev/dancing-bot.jpg',
        price: 59.99,
        category: 'Electronics',
        description: '',
    },
    {
        id: '7',
        name: 'Bio Doll',
        img: '/images/dev/bio-doll.jpg',
        price: 39.99,
        category: 'Dolls',
        description: '',
    },
    {
        id: '8',
        name: 'Bluestone Ring',
        img: '/images/dev/bluestone-ring.jpg',
        price: 124.99,
        category: 'Jewelry',
        description: '',
    },
    {
        id: '9',
        name: 'Cat Doll',
        img: '/images/dev/cat-doll.jpg',
        price: 74.99,
        category: 'Dolls',
        description: '',
    },
];